export const TYPE_COLORS: Record<string, { card: string; image: string; text: string }> = {
    normal: { card: 'bg-normal', image: 'bg-normal/50', text: 'text-black' },
    fire: { card: 'bg-fire', image: 'bg-fire/50', text: 'text-black' },
    water: { card: 'bg-water', image: 'bg-water/50', text: 'text-black' },
    electric: { card: 'bg-electric', image: 'bg-electric/50', text: 'text-black' },
    grass: { card: 'bg-grass', image: 'bg-grass/50', text: 'text-black' },
    ice: { card: 'bg-ice', image: 'bg-ice/50', text: 'text-black' },
    fighting: { card: 'bg-fighting', image: 'bg-fighting/50', text: 'text-white' },
    poison: { card: 'bg-poison', image: 'bg-poison/50', text: 'text-white' },
    ground: { card: 'bg-ground', image: 'bg-ground/50', text: 'text-black' },
    flying: { card: 'bg-flying', image: 'bg-flying/50', text: 'text-black' },
    psychic: { card: 'bg-psychic', image: 'bg-psychic/50', text: 'text-black' },
    bug: { card: 'bg-bug', image: 'bg-bug/50', text: 'text-black' },
    rock: { card: 'bg-rock', image: 'bg-rock/50', text: 'text-black' },
    ghost: { card: 'bg-ghost', image: 'bg-ghost/50', text: 'text-white' },
    dragon: { card: 'bg-dragon', image: 'bg-dragon/50', text: 'text-white' },
    dark: { card: 'bg-dark', image: 'bg-dark/50', text: 'text-white' },
    steel: { card: 'bg-steel', image: 'bg-steel/50', text: 'text-black' },
    fairy: { card: 'bg-fairy', image: 'bg-fairy/50', text: 'text-black' },
}
